#!/usr/bin/env bash

set -Eeuo pipefail
HOST=dragon

log() {
  local line="${1}"
  echo "${line}" >&2
}

remote_run() {
  local host="${1}" cmd="${2}"
  cmd="set -Eeuo pipefail && ${cmd}"
  log "Running on ${host}:"
  log "${cmd}"
  ssh "${host}" "${cmd}"
}

source etc/door-eye/app.env

cmd="mkdir -p /etc/door-eye && mkdir -p ${JSON_PATH%/*} && apt-get install -y socat mpv rsync"
remote_run "${HOST}" "${cmd}"

rsync -ae ssh etc/door-eye/*.env $HOST:/etc/door-eye/
rsync -ae ssh bin/* $HOST:/usr/local/bin/
rsync -ae ssh systemd/* $HOST:/etc/systemd/system/

UNMANAGED_UNITS="show-door-screen.service update-door-eye-osd.service"

cmd="systemctl daemon-reload"
for unit in `ls systemd`; do
  if [[ " ${UNMANAGED_UNITS} " == *" ${unit} "* ]]; then
    cmd="${cmd} && systemctl disable ${unit} || true"
    cmd="${cmd} && systemctl stop ${unit} || true"
  else
    cmd="${cmd} && systemctl enable ${unit}"
    cmd="${cmd} && systemctl restart ${unit}"
  fi
done

remote_run "${HOST}" "${cmd}"

echo "App successfully deployed"
