#!/usr/bin/env bash

set -Eeuo pipefail
HOST=dragon

log() {
  local line="${1}"
  echo "${line}" >&2
}

remote_run() {
  local host="${1}" cmd="${2}"
  cmd="set -Eeuo pipefail && ${cmd}"
  log "Running on ${host}:"
  log "${cmd}"
  ssh "${host}" "${cmd}"
}

source etc/door-eye/app.env

PACKAGES="socat mpv rsync \
pipewire pipewire-bin pipewire-audio pipewire-pulse wireplumber \
libspa-0.2-bluetooth bluez"

cmd="mkdir -p /etc/door-eye"
cmd="${cmd} && mkdir -p ${JSON_PATH%/*}"
cmd="${cmd} && mkdir -p /etc/wireplumber/wireplumber.conf.d"
cmd="${cmd} && apt-get install -y ${PACKAGES}"
remote_run "${HOST}" "${cmd}"

rsync -ae ssh etc/door-eye/*.env $HOST:/etc/door-eye/
rsync -ae ssh etc/wireplumber/wireplumber.conf.d/* $HOST:/etc/wireplumber/wireplumber.conf.d/
rsync -ae ssh bin/* $HOST:/usr/local/bin/
rsync -ae ssh systemd/* $HOST:/etc/systemd/system/

cmd="systemctl daemon-reload"
for unit in `ls systemd`; do
  cmd="${cmd} && systemctl enable ${unit}"
  cmd="${cmd} && systemctl restart ${unit}"
done

remote_run "${HOST}" "${cmd}"

echo "App successfully deployed"
