#!/usr/bin/env bash

set -Eeuo pipefail
HOST=orangepi


ssh $HOST mkdir -p /etc/door-eye
rsync -ae ssh etc/door-eye/*.env $HOST:/etc/door-eye/
rsync -ae ssh bin/* $HOST:/usr/local/bin/
rsync -ae ssh systemd/* $HOST:/etc/systemd/system/

cmd="set -Eeuo pipefail"
cmd="${cmd} && source /etc/door-eye/app.env"
cmd="${cmd} && mkdir -p \${LIB_DIR}"
cmd="${cmd} && systemctl daemon-reload"
for unit in `ls systemd`; do
  cmd="${cmd} && systemctl enable ${unit}"
  cmd="${cmd} && systemctl restart ${unit}"
done

echo "Running \`${cmd}\` on ${HOST}"
ssh $HOST 'bash -c "${cmd}"'

echo "App successfully deployed"
